# aljabar matriks

1. Berikan penjelasan tentang apa itu matriks
2. Operasi matriks
    
    A. penjumlahan

    B. perkalian

    C. pengurangan

    D. transpose matriks
3. Buat program untuk mengalikan matrik A dan B tidak menggunakan "@"
4. membuat matriks A dan B dengan ordo 3X3 dan matriks C dengan ordo 3X2

## Jawaban

## 1. Aljabar Matriks



Matriks adalah sebuah susunan bilangan real/bilanagn lomplek(elemen-elemen) yang tersusun dalam bentuk baris dan kolom sehingga membentuk jajaran persegi panjangmatrix dibri nama menggunakan huruf kapital seperti A,B,C, dan serterusnya. matrix di lambangkna dengan 0.


## 2.operasi matrix

**A. Penjumlahan Matriks:**

Penjumlahan matriks hanya dapat dilakukan pada matriks dengan dimensi yang sama. Elemen yang memiliki posisi sama pada kedua matriks dijumlahkan.

**Contoh:**

Misalkan matriks A dan B berukuran 2x2:

```
A = [2 1]
    [7 8]

B = [4 7]
    [2 5]
```

Maka penjumlahan matriks A dan B adalah:

```
A + B = [2+4 1+7]
        [7+2 8+5]

       = [6 8]
         [9 13]
```

**B. Perkalian Matriks:**

Perkalian matriks berbeda dengan perkalian bilangan biasa. Perkalian matriks melibatkan perkalian elemen-elemen matriks dan penjumlahan hasil perkaliannya.

**Contoh:**

Misalkan matriks A berukuran 2x2 dan matriks B berukuran 2x3:

```
A = [1 2]
    [3 4]

B = [5 6 7]
    [8 9 10]
```

Maka penjumlahan matriks A dan B adalah:

```
A + B = [2+4 1+7]
        [7+2 8+5]

       = [6 8]
         [9 13]
```


``````
Maka perkalian matriks A dan B adalah:

```
A * B = [1*5+2*8 1*6+2*9 1*7+2*10]
        [3*5+4*8 3*6+4*9 3*7+4*10]

       = [21 24 33]
        [49 60 77]
```


**C. Pengurangan Matriks:**

Pengurangan matriks dilakukan dengan cara yang sama seperti penjumlahan matriks, yaitu dengan mengurangkan elemen yang memiliki posisi sama pada kedua matriks.

**Contoh:**

Misalkan kita memiliki dua matriks A dan B berikut:

```
A = [[3, 1], [2, 5]]
B = [[2, 3], [3, 4]]
```

Untuk mengurangkan matriks A dan B, kita perlu mengurangkan elemen-elemen matriks yang seletak.

```
A - B = [[3 - 2, 1 - 3], [2 - 4, 5 - 4]]
```

Hasil pengurangan matriks A dan B adalah matriks berikut:

```
C = [[1, -2], [-2, 1]]
```

\
**D. Transpose Matriks:**

Transpose matriks adalah operasi yang mengubah baris menjadi kolom dan kolom menjadi baris.

**Contoh:**

Misalkan matriks A berukuran 2x2:

```
A = [2 1 0]
    [1 0 2]
```

Maka transpose matriks A adalah:

```
A^T = [2 1]
      [1 0]
```   [0 8]




## Aplikasi Matriks

1. Penjumlahan dan Pengurangan Matriks: Dilakukan antara matriks dengan dimensi yang sama, yaitu jumlah baris dan kolom yang identik.

2. Perkalian Matriks: Dilakukan antara matriks yang memenuhi aturan perkalian matriks, yaitu jumlah baris dan kolom kedua matriks harus sama.

3. Inverse Matriks: Digunakan untuk membalikkan efek perkalian matriks.

4. Determinan Matriks: Dilakukan antara matriks yang memenuhi aturan perkalian matriks, yaitu jumlah baris dan kolom kedu

5. Transpos matriks: proses mengubah baris matriks menjadi kolom atau sebaliknya

## 3. operasi tranpose Matriks

Berikut adalah program Python untuk mengalikan matriks A dan B secara manual menggunakan perulangan:

In [ ]:
def multiply_matrices(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    # Membuat matriks hasil dengan ukuran yang sesuai
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perkalian matriks
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result

# Matriks A
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# Matriks B
B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

# Mengalikan dua matriks
C = multiply_matrices(A, B)

# Menampilkan hasil
for row in C:
    print(row)

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


Transpose matriks adalah sebuah matriks baru yang dibuat dengan cara menukar elemen baris menjadi elemen kolom atau sebaliknya. Matriks transpose memiliki karakteristik berikut.

(A + B)T = (A)T + (B)T

(AT)T = A

(AB)T = (A)T (B)T

(kA)T = k.AT, dengan k = konstanta

Cara Mengerjakan

Cara Melakukannya

Matriks A memiliki elemen yang disusun dengan cara berikut:

baris pertama a dan b, baris kedua c dan d, dan baris ketiga e dan f. Kolom pertama a, c, dan e, dan kolom kedua b, d, dan f.

Karena itu, susunan transpose matriks A adalah sebagai berikut:

baris pertama a, c, dan e; baris kedua b, d, dan f; kolom pertama a dan b; kolom kedua c dan d; dan kolom ketiga e dan f.

###4. Program perkalian matrix

In [ ]:
#membuat struktur matriks
import numpy as np
import sympy as sy

#mendefinisikan matrik a
a=np.array([[2,7,1],[6,1,9],[2,3,7]])
#mendefinisikan matfrik b
b=np.array([[1,4,7],[6,1,5],[1,4,3]])
#operasi perkalian matrik

# Inisialisasi matriks hasil perkalian dengan ukuran yang sesuai
hasil =np.array([[0,0,0],[0,0,0],[0,0,0]])
# Melakukan perkalian matriks
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            hasil[i][j] += a[i][k] * b[k][j]

# Tampilkan hasil
for baris in hasil:
    print(baris)


[45 19 52]
[21 61 74]
[27 39 50]


Perkalian Matriks 3x3: Perkalian dua matriks berukuran 3x3 akan menghasilkan matriks baru berukuran 3x3. Cara melakukannya adalah sebagai berikut.

 Perkalian matriks 3 kali 3.

1. Pertama, kalikan baris pertama matriks A dengan kolom pertama matriks B. Anggota bilangan pada baris pertama dan kolom pertama hasil perkalian akan dihasilkan.

2. Matriks B’s kolom kedua dikalikan dengan baris pertamanya. Hasil perkalian akan menjadi anggota bilangan pada baris pertama dan kolom kedua matriks.

3. Matriks B’s kolom ketiga dikalikan dengan baris pertamanya. Hasil perkalian akan menjadi anggota bilangan pada baris pertama dan kolom ketiga yang dihasilkan dari perkalian.

4. Kalikan baris kedua matriks A dengan kolom pertama matriks B. Anggota angka pada baris kedua dan kolom pertama hasil perkalian akan dihasilkan.

5. Kalikan baris kedua matriks A dengan kolom kedua matriks B. Anggota bilangan pada baris kedua dan kolom kedua hasil perkalian akan dihasilkan.

6. Kalikan baris kedua matriks A dengan kolom ketiga matriks B. Hasilnya akan menjadi anggota bilangan pada baris kedua dan kolom ketiga matriks yang dihasilkan dari perkalian.

6. Kalikan baris ketiga matriks A dengan kolom pertama matriks B. Anggota angka pada baris ketiga dan kolom pertama hasil perkalian akan dihasilkan.

7. Matriks B’s kolom kedua harus dikalikan dengan baris ketiga matriks A. Hasilnya akan menjadi anggota bilangan pada baris ketiga dan kolom kedua matriks perkalian.

8. Kalikan baris ketiga matriks A dengan kolom ketiga matriks B. Anggota bilangan pada baris ketiga dan kolom ketiga hasil perkalian akan dihasilkan.