# determinal matrik



## 1

In [ ]:
import numpy as np
A = ([[1,0],[0,1]])
determinan = np.linalg.det(A)
print("Determinan dari  matriks identitas ordo (2x2) adalah:", int(determinan))

B=([[1,0,0],[0,1,0],[0,0,1]])
determinan_B = np.linalg.det(B)
print("Determinan dari matriks identitas ordo (2x2) adalah:", int(determinan))

Determinan dari  matriks identitas ordo (2x2) adalah: 1
Determinan dari matriks identitas ordo (2x2) adalah: 1


## 2

In [ ]:
import numpy as np
C = ([[1,2,1], [3,1,2], [2,1,2]])
determinan = np.linalg.det(C)
print("determinan matriks adalah:", int(determinan))

determinan matriks adalah: -3


## 3

In [ ]:
import numpy as np
D = ([[3,1,2], [1,2,1], [2,1,2]])
determinan = np.linalg.det(D)
print("determinan matriks adalah:", int(determinan))

determinan matriks adalah: 3


## 4

In [ ]:
import numpy as np
E = ([[1,2,1], [2,4,2], [2,1,2]])
determinan = np.linalg.det(E)
print("determinan matriks adalah:", int(determinan))

determinan matriks adalah: 0


## 5

In [ ]:
import numpy as np
F = ([[1,2,1], [2,4,2], [2,4,3]])
determinan = np.linalg.det(F)
print("determinan matriks adalah:", int(determinan))

determinan matriks adalah: 0


In [ ]:
import numpy as np
G = ([[6,2,4], [2,4,2], [4,2,4]])
determinan = np.linalg.det(G)
print("determinan matriks adalah:", int(determinan))

determinan matriks adalah: 24


In [ ]:
import numpy as np
H = ([[6,8], [4,2]])
determinan = np.linalg.det(H)
print("determinan matriks adalah:", int(determinan))

determinan matriks adalah: -19


In [ ]:
import numpy as np
T= 2
A = ([[3,4],[2,1]])
determinan = np.linalg.det(A)
hasil = determinan *2
print("Determinan dari matriks A adalah:", int(hasil.round()))


I = ([[3*T,4*T],[2,1]])
determinan_I = np.linalg.det(I)
print("Determinan dari matriks I adalah:", int(determinan_I.round()))

Determinan dari matriks A adalah: -10
Determinan dari matriks I adalah: -10


## 6

In [ ]:
import numpy as np
A2 =([[7,5],[2,1]])
determinan =np.linalg.det(A2)
print (A2, "\n")
print("determinan dari matriks A2 adalah:", int(determinan.round()))

A =([[4,1],[2,1]])
determinan_A =np.linalg.det(A)
print (A, "\n")
print("determinan dari matriks A adalah:", int(determinan_A.round()))

B =([[3,2],[2,1]])
determinan_B =np.linalg.det(B)
print (B, "\n")
print("determinan dari matriks B adalah:", int(determinan_B.round()))

[[7, 5], [2, 1]] 

determinan dari matriks A2 adalah: -3
[[4, 1], [2, 1]] 

determinan dari matriks A adalah: 2
[[3, 2], [2, 1]] 

determinan dari matriks B adalah: -1


In [ ]:
import numpy as np
A2 =([[7,5],[2,1]])
determinan =np.linalg.det(A2)
print("determinan dari matriks A2 adalah:", int(determinan.round()))

A =([[4,1],[2,1]])
determinan_A =np.linalg.det(A)
print("determinan dari matriks A adalah:", int(determinan_A.round()))

B =([[3,2],[2,1]])
determinan_B =np.linalg.det(B)
print("determinan dari matriks B adalah:", int(determinan_B.round()))

determinan dari matriks A2 adalah: -3
determinan dari matriks A adalah: 2
determinan dari matriks B adalah: -1


## 7

In [ ]:
import numpy as np
A =np.array ([[1,3,2],[0,2,2],[0,0,1]])
determinan =np.linalg.det(A)
print(A, "\n")
print("determinan matriks adalah:", int(determinan))

[[1 3 2]
 [0 2 2]
 [0 0 1]] 

determinan matriks adalah: 2


In [ ]:
import numpy as np
A =np.array ([[2,1,5],[0,4,1],[0,0,2]])
determinan =np.linalg.det(A)
print(A, "\n")
print("determinan matriks adalah:", int(determinan))

[[2 1 5]
 [0 4 1]
 [0 0 2]] 

determinan matriks adalah: 15


## tugas baru
menghitung det mat dan invers mat
menghitung invers matriks 5x5 dengan kofaktor yang di transposekan

Untuk menghitung invers matriks
5×5 menggunakan metode kofaktor yang ditransposekan, ikuti langkah-langkah berikut:

Langkah 1: Hitung Determinan Matriks
Untuk menemukan invers suatu matriks, Anda pertama-tama harus memastikan bahwa determinannya tidak sama dengan nol. Determinan matriks
𝐴
A dapat dihitung menggunakan metode ekspansi kofaktor. Misalkan
𝐴
A adalah matriks
5
×
5:

\begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14} & a_{15} \\
a_{21} & a_{22} & a_{23} & a_{24} & a_{25} \\
a_{31} & a_{32} & a_{33} & a_{34} & a_{35} \\
a_{41} & a_{42} & a_{43} & a_{44} & a_{45} \\
a_{51} & a_{52} & a_{53} & a_{54} & a_{55} \\
\end{pmatrix} \]

Determinannya, \( \det(A) \), dihitung dengan ekspansi kofaktor pada baris pertama (atau baris/kolom lain):
\[ \det(A) = \sum_{j=1}^{5} (-1)^{1+j} a_{1j} \det(A_{1j}) \]
Di mana \( A_{1j} \) adalah submatriks \( 4 \times 4 \) yang diperoleh dengan menghapus baris pertama dan kolom \( j \) dari matriks \( A \).
### Langkah 2: Hitung Matriks Kofaktor
Untuk setiap elemen \( a_{ij} \) dari matriks \( A \), hitung kofaktornya, \( C_{ij} \), yang didefinisikan sebagai:
\[ C_{ij} = (-1)^{i+j} \det(A_{ij}) \]
Di mana \( A_{ij} \) adalah submatriks \( 4 \times 4 \) yang diperoleh dengan menghapus baris \( i \) dan kolom \( j \) dari \( A \).
### Langkah 3: Bentuk Matriks Kofaktor
Buat matriks kofaktor \( C \) dari semua kofaktor \( C_{ij} \):
\[ C = \begin{pmatrix}
C_{11} & C_{12} & C_{13} & C_{14} & C_{15} \\
C_{21} & C_{22} & C_{23} & C_{24} & C_{25} \\
C_{31} & C_{32} & C_{33} & C_{34} & C_{35} \\
C_{41} & C_{42} & C_{43} & C_{44} & C_{45} \\
C_{51} & C_{52} & C_{53} & C_{54} & C_{55}
\end{pmatrix} \]
### Langkah 4: Transpos Matriks Kofaktor
Transposkan matriks kofaktor untuk mendapatkan matriks adjugat \( \text{adj}(A) \):
\[ \text{adj}(A) = C^T \]
### Langkah 5: Hitung Invers Matriks
Akhirnya, invers dari matriks \( A \) diberikan oleh:
\[ A^{-1} = \frac{1}{\det(A)} \text{adj}(A) \]
### Contoh
Misalkan \( A \) adalah:
\[ A = \begin{pmatrix}
2 & -1 & 0 & 0 & 1 \\
1 & 3 & 2 & 0 & -1 \\
0 & 1 & -1 & 4 & 2 \\
3 & 0 & -2 & 1 & 3 \\
1 & 2 & 3 & 1 & -1
\end{pmatrix} \]
Langkah-langkah lengkap untuk menghitung determinan, matriks kofaktor, dan matriks adjugat secara manual sangat panjang, sehingga disarankan menggunakan alat bantu seperti software matematika (contohnya MATLAB, Python dengan NumPy, atau kalkulator matriks) untuk mengurangi risiko kesalahan dan mempercepat proses perhitungan.

In [ ]:
import numpy as np

# Definisikan matriks 5x5
A = np.array([
    [2, -1, 0, 0, 1],
    [1, 3, 2, 0, -1],
    [0, 1, -1, 4, 2],
    [3, 0, -2, 1, 3],
    [1, 2, 3, 1, -1]
])

# Pastikan determinan tidak nol
det_A = np.linalg.det(A)
if det_A == 0:
    raise ValueError("Matriks tidak memiliki invers karena determinannya nol.")

# Hitung invers matriks menggunakan fungsi bawaan NumPy
A_inv = np.linalg.inv(A)

print("Matriks A:")
print(A)
print("\nInvers dari matriks A:")
print(A_inv)
